/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simplest.possible.implementation;
import java.util.ArrayList;
import java.util.List;

public class Library {
    public List of(int number) {
        List list = new ArrayList();
        if (number == 1)
            list.removeAll(list);
        return list;
    }
}
